COPY INTO WINE.PUBLIC.WINE_QUALITY
    FROM @~/staged/winequality.csv
    FILE_FORMAT = (
        TYPE=CSV,
        SKIP_HEADER=1,
        FIELD_DELIMITER=',',
        TRIM_SPACE=FALSE,
        FIELD_OPTIONALLY_ENCLOSED_BY=NONE,
        DATE_FORMAT=AUTO,
        TIME_FORMAT=AUTO,
        TIMESTAMP_FORMAT=AUTO
    )
    ON_ERROR=ABORT_STATEMENT
    PURGE=TRUE